config/routes.rb
Rails.application.routes.draw do
  resources :products, only:[:index, :new, :create, :destroy]
  
  resources :cart_items, only:[:create, :destroy]
  
  resources :carts, only:[:show]
  
  root 'top#main'
  get 'top/main'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  validates :product_id, presence: true
  validates :cart_id, presence: true
  validates :qty, presence: true
  
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, numericality: { only_integer: true }
  
  has_many :cart_items, source: :cart, through: :cart_items
  has_many :carts, through: :cart_items
  belongs_to :cart

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
    def current_cart
      if session[:cart_id]
        cart = Cart.find(session[:cart_id])
      else
        cart = Cart.create
        session[:cart_id] = cart.id
      end
      cart
    end
    helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    cart = current_cart
    cart.cart_items.create(product_id: product.id, cart_id: cart.id, qty: params[:qty])
    redirect_to cart_path(current_cart.id)
  end
  
  def destroy
    CartItem.find(params[:id]).destroy
    redirect_to cart_path(current_cart.id)
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart_items = CartItem.where(cart_id: current_cart)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
     if @product.save
       redirect_to products_path
     else
       render 'new'
     end
  end
   
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h2>カート</h2>

<% total = 0 %>
<% @cart_items.each do |item| %>
  <%= item.product.name %>
  &ensp;&ensp;
  <%= "価格: ¥" %>
  <%= item.product.price %>
  &ensp;&ensp;
  <%= "数量:" %>
  <%= item.qty %>
  &ensp;&ensp;
  <%= link_to '削除', cart_item_path(item), method: :delete %>
  <br/>
  <% total = total + item.product.price.to_i * item.qty.to_i %>
<% end %>
  <br/><hr><br/>
  <%= "合計金額: ¥" %>
  <%= total %>

<br/><br/>

<%= link_to '買い物を続ける', top_main_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>
<hr>
<% @products.each do |p| %>
  <%= p.name %>
  &ensp;
  <%= p.price %>
  <%= "円" %>
  &ensp;&ensp;
  
  <%= link_to '削除', product_path(p), method: :delete %>
  <br/><br/>
<% end %>

<p><%= link_to '新規登録', new_product_path %></p>
<p><%= link_to 'Topページへ', root_path %></p>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
  <%= f.label :name, '商品名' %>
  <%= f.text_field :name %>
  <%= f.label :price, '値段' %>
  <%= f.text_field :price %>
  <%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>ショッピングサイト</h1>
<hr>
<% @products.each do |product| %>
  <%= product.name %>
  &ensp;
  <%= product.price %>
  <%= "円" %>
  &ensp;
 
  &ensp;&ensp;
  <%= form_tag cart_items_path(product_id: product.id) do %>
  <%= text_field_tag :qty, 1, size: 2 %>
  <%= submit_tag 'カートに入れる' %>
  <% end %>
  <br/><br/>
<% end %>

<p><%= link_to 'カート', cart_path(current_cart.id) %></p>
<p><%= link_to '商品一覧', products_path %></p>